name: Wake Up Websites
favicon: null
layout_spectrum: 0.6949638633523136
typography_spectrum: 0.13646150706335902
title: Unlimited Website Maintenance
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.7154968250542879
  lightness: 0.0884944461286068
  saturation: 0.09902211744338274
  rhythmicContrast: 0.3126600494142622
purpose: []
